# Generated by Django 5.2.1 on 2025-05-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('limit', models.IntegerField(default=0, verbose_name='Limit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Inactive'), (2, 'Active'), (3, 'Expired'), (4, 'Completed'), (5, 'Excluded')], default=0, verbose_name='Status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='event_app.event', verbose_name='Event')),
            ],
            options={
                'db_table': 'db_batches',
            },
        ),
    ]
