# Generated by Django 5.2.1 on 2025-06-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Debit Card'), (3, 'Pix'), (4, 'Billet')], null=True),
        ),
    ]
